### ISSUE TITLE
SDF values

### ISSUE THREAD

**Issue by grau4** [autonomousvision/convolutional_occupancy_networks#12]
Hi Songyou,

thank you for making your excellent work publicly available.

My question is rather general: When using your architecture, is there any particular reason that keeps you from computing SDF values instead of binary occupancy?

**Comment by pengsongyou** [comment]
Hi @grau4 ,

Thanks a lot for your kind words! Indeed, we can definitely also use SDF instead of SDF. One reason could be: SDF prediction is a regression problem, while occupancy prediction is a classification one. Therefore, it should be easier for a network to learn. But there are also some really nice properties of SDF, but when we were focusing more on how to scale up the [Occupancy Networks](https://avg.is.tuebingen.mpg.de/publications/occupancy-networks), so we directly went in the direction of predicting occupancy.

Hope this answers your question :) 

Best, 
Songyou

**Comment by grau4** [comment]
Thank you for the prompt answer :)

Best regards.
