### ISSUE TITLE
Evaluation and visualization

### ISSUE THREAD

**Issue by zgojcic** [autonomousvision/convolutional_occupancy_networks#23]
Hi @pengsongyou,

thank you for open-sourcing the code. I would have two questions regarding the evaluation:

- In the code I have observed that you have a function `refine_mesh `, which performs an optimization of the mesh after MC. Is this function used for the evaluation or visualizations? In all config files refine is set to False. 
- What exactly does you mean with "To ensure a fair comparison to SPSR, we compare all methods with only a single
surface for walls/ground planes when calculating Chamfer-L1 and F-Score.". Do you remove all but one floor/wall? Is this also reflected in the computation of the IoU?

Thanks in advance,

Zan

**Comment by pengsongyou** [comment]
Hi Zan @zgojcic ,

Thanks so much for your interest in our work.

* We modified the generation code directly from Occupancy Networks' code, and forgot to delete much stuff, e.g. `refine_mesh`. Therefore, `refine_mesh` is not used at all.
* Because SPSR with trimming gives reconstruction with only single surfaces for walls/ground planes, we cannot evaluate IoU for SPSR. In contrast, our method always reconstructs walls/ground planes with some thickness (double sides) and it is always watertight (so we can evaluate IoU). To fairly compare with SPSR on Chamfer and F-Score, we also keep only the inner surface and remove the outer surface for walls/ground planes. This is not reflected in the computation of IoU.

Best,
Songyou

**Comment by zgojcic** [comment]
Hi Songyou, 

this makes a lot of sense, thanks for the fast response. 

Best
Zan
