### ISSUE TITLE
why normalize_3d_coordiante is needed?

### ISSUE THREAD

**Issue by qiminchen** [autonomousvision/convolutional_occupancy_networks#34]
Hi, I'm wondering why normalize_3d_coordiante is needed if the point coordinate is in range of `[-0.5, 0.5]`?
https://github.com/autonomousvision/convolutional_occupancy_networks/blob/f44d413f8d455657a44c24d06163934c69141a09/src/encoder/voxels.py#L74

**Comment by pengsongyou** [comment]
Hi @qiminchen,

If you check https://github.com/autonomousvision/convolutional_occupancy_networks/blob/f44d413f8d455657a44c24d06163934c69141a09/src/common.py#L260
you can notice that we normalize the coordinates to the range of `[0, 1]` with the padding as well (since we define the entire 3D space in the range of `[-0.55, 0.55]`). With the normalized coordintes, we can easily calculate the indices, which is later used for `scatter_mean` operation.

Hope it answers your questions.

**Comment by qiminchen** [comment]
thanks, that makes sense, is there any reason you define the 3d space in the range of `[-0.55, 0.55]`? If the 3d space is in the range of `[-0.5, 0.5]` (which I guess it's more common?), `padding` should be set to 0, right?

**Comment by pengsongyou** [comment]
> thanks, that makes sense, is there any specific reason you define the 3d space in the range of `[-0.55, 0.55]`? If the 3d space is in the range of `[-0.5, 0.5]` (which I guess it's more common?), `padding` should be set to 0, right?

We were using the ShapeNet data processed and provided by [Occupancy Networks](https://github.com/autonomousvision/occupancy_networks), where they define the 3D space in the range of `[-0.55, 0.55]`, so we simply followed it. You are right, if your space is in the range of `[-0.5, 0.5]`, then you can set `padding` to 0.

**Comment by qiminchen** [comment]
great, thank you
